[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "phpPackages.php", "nginx", "libmysqlclient"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev"]

[phases.build]
cmds = []

[phases.start]
cmds = [
  "php artisan serve --host=0.0.0.0 --port=$PORT"
]
